language: c++
branches:
  only:
  - master
cache:
  ccache: true
  directories:
   - deno2/js/node_modules/
   - deno2/v8
   - $DEPOT_TOOLS_PATH
env:
  global:
    - BUILD_PATH=$HOME/out/Debug
    - DEPOT_TOOLS_PATH=$HOME/depot_tools
before_install: |
  if ! [ -x $DEPOT_TOOLS_PATH/gclient ]; then
    rm -rf $DEPOT_TOOLS_PATH
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $DEPOT_TOOLS_PATH
  fi
install:
 - env
 - export PATH=$PATH:$DEPOT_TOOLS_PATH
 - cd deno2
 - gclient sync --no-history
 - (cd js; yarn)
 - gn gen $BUILD_PATH --args='cc_wrapper="ccache"'
 - ninja -j3 -C $BUILD_PATH mock_runtime_test deno
script:
 - $BUILD_PATH/mock_runtime_test
